apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-nfs-v0
  labels:
    type: local
spec:
  storageClassName: rabbitnfs
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.80
    path: "/mnt/rabbits/v0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-nfs-v1
  labels:
    type: local
spec:
  storageClassName: rabbitnfs
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.80
    path: "/mnt/rabbits/v1"

